#!/bin/sh

#
# Copyright 2015 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
  echo "$*"
}

die () {
  echo
  echo "$*"
  echo
  exit 1
}

# OS specific support functions.
#
# In order to support multiple platforms, this script delegates to functions
# extracted into os-specific scripts.
# shellcheck disable=SC2034,SC3043
cygwin=false
msys=false
Darwin=false
case "`uname`" in
  CYGWIN* ) cygwin=true ;;
  MINGW* ) msys=true ;;
  Darwin* ) Darwin=true ;;
  MSYS* ) msys=true ;;
esac

# For Cygwin or MSYS, ensure paths are in UNIX format before anything is touched.
if [ "$cygwin" = "true" ] || [ "$msys" = "true" ]; then
  APP_HOME=`cygpath --unix "$APP_HOME"`
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    # IBM's JDK on AIX uses strange locations for the executables
    JAVACMD="$JAVA_HOME/jre/sh/java"
  else
    JAVACMD="$JAVA_HOME/bin/java"
  fi
  if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
  fi
else
  JAVACMD="java"
  which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" ] && [ "$Darwin" = "false" ] ; then
  case "$MAX_FD" in
    max*)
      MAX_FD=`ulimit -H -n`
      if [ $? -ne 0 ] ; then
        warn "Could not query maximum file descriptor limit"
        MAX_FD=""
      fi
    ;;
  esac
  if [ "$MAX_FD" != "" ] ; then
    ulimit -n $MAX_FD 2>/dev/null || warn "Could not set maximum file descriptor limit to $MAX_FD"
  fi
fi

# For Darwin, add the Apple specific Java options.
if $Darwin ; then
  if [ "$HOME" = "$PWD" ]; then
    cd "$APP_HOME"
  fi
  if [ -z "$JAVA_OPTS" ]; then
    JAVA_OPTS="-XstartOnFirstThread"
  else
    JAVA_OPTS="-XstartOnFirstThread $JAVA_OPTS"
  fi
fi

# Escape application args.
save () {
  for i in "$@" ; do
    printf %s\n "$i" | sed "s/'/'\\''/g"
  done
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
